/* import type { Metadata } from "next"; */
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.scss";
import { Header } from "@/components/Header";

const inter = Inter({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    preload: true,
});

/* export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}; */

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <hr className="headerHr" />
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
